force-app/main/default/objects/Flight_Bookings__c/Flight_Bookings__c.object-meta.xml
<CustomObject>
    <label>Flight Bookings</label>
    <nameField>
        <displayFormat>FB-{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Bookings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flights Bookings</relationshipLabel>
    <relationshipName>Flights_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tourist</fullName>
            </value>
            <value>
                <fullName>First Class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Flights Bookings</relationshipLabel>
    <relationshipName>Flights_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TODAY())</defaultValue>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Bruselas</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Bruselas</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EJ1TriggersTest.cls
@isTest
public class EJ1TriggersTest {
	@isTest
    public static void testInsert(){
        Account acc = new Account(Name='Account for test');
        insert acc;
        Contact cont = new Contact(FirstName='Name', LastName='Test',
                                  AccountId = acc.Id);
        insert cont;
        DateTime depDate = Date.today().addDays(2);
        Flight_Bookings__c fb = new Flight_Bookings__c(Origin__c='Madrid', Destination__c='Bruselas', Class__c='Tourist',
                                                  Departure_Date__c=depDate, Contact__c = cont.Id);
        insert fb;
        List<Flight_Bookings__c> listFlightBooking = [SELECT Account__c FROM Flight_Bookings__c WHERE id =: fb.Id];
        System.assertEquals(cont.AccountId, listFlightBooking[0].Account__c);
    }
    @isTest
    public static void testModify(){
        Account acc = new Account(Name='Account for test 2');
        insert acc;
        Contact cont = new Contact(FirstName='Name', LastName='Test Two',
                                  AccountId = acc.Id);
        insert cont;
        DateTime depDate = DateTime.newInstance(DateTime.now().getTime()).addDays(2);
        Flight_Bookings__c fb = new Flight_Bookings__c(Origin__c='Madrid', Destination__c='Bruselas', Class__c='Tourist',
                                                  Departure_Date__c=depDate, Contact__c = cont.Id, Account__c = acc.Id);
        insert fb;
        
        fb.Destination__c = 'Paris';
        update fb;
        List<Flight_Bookings__c> listFlightBooking = [SELECT Modified__c FROM Flight_Bookings__c WHERE id =: fb.Id];
        System.assertEquals(true, listFlightBooking[0].Modified__c);
    }
}