force-app/main/default/objects/Contact/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <label>NIF</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/Flight_Bookings__c.object-meta.xml
<CustomObject>
    <label>Flight Bookings</label>
    <nameField>
        <displayFormat>FB-{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Bookings__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flights Bookings</relationshipLabel>
    <relationshipName>Flights_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tourist</fullName>
            </value>
            <value>
                <fullName>First Class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Flights Bookings</relationshipLabel>
    <relationshipName>Flights_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TODAY())</defaultValue>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Bruselas</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight_Bookings__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Bruselas</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger__c/fields/Flight_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Flight_Bookings__c</fullName>
    <label>Flight Bookings</label>
    <referenceTo>Flight_Bookings__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Passenger__c/fields/ID_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Card__c</fullName>
    <label>ID Card</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EJ2TriggerTest.cls
@isTest
public class EJ2TriggerTest {
    @isTest
    public static void testInsert(){
        Contact con = new Contact(FirstName='Test', LastName='1', NIF__c='73429409T');
        insert con;
        Account acc = new Account(Name= 'SALES');
        insert acc;
        DateTime depDate = Date.today().addDays(2);
        Flight_Bookings__c fb = new Flight_Bookings__c(Origin__c='Madrid', Destination__c='Bruselas', Class__c='Tourist',
                                                  Departure_Date__c=depDate, Contact__c = con.Id, Account__c = acc.Id);
        insert fb;
        Passenger__c pas = new Passenger__c(ID_Card__c='73429409T', Age__c = 22, Name='Pepe', Flight_Bookings__c=fb.Id);
        System.debug(pas);
        insert pas;
        List<Passenger__c> listPass = [SELECT ID_Card__c FROM Passenger__c WHERE ID_Card__c =: con.NIF__c];
        System.assertEquals(con.NIF__c, listPass[0].ID_Card__c);

    }
    @isTest
    public static void testBreak(){
        Contact con = new Contact(FirstName='Test', LastName='1', NIF__c='73429409T');
        insert con;
        Account acc = new Account(Name= 'SALES');
        insert acc;
        DateTime depDate = Date.today().addDays(2);
        Flight_Bookings__c fb = new Flight_Bookings__c(Origin__c='Madrid', Destination__c='Bruselas', Class__c='Tourist',
                                                  Departure_Date__c=depDate, Contact__c = con.Id, Account__c = acc.Id);
        insert fb;
        Passenger__c pas = new Passenger__c(ID_Card__c='734294R', Age__c = 22, Name='Pepe', Flight_Bookings__c=fb.Id);
        System.debug(pas);
        insert pas;
        List<Passenger__c> listPass = [SELECT ID_Card__c FROM Passenger__c WHERE ID_Card__c =: con.NIF__c];
        System.assertNotEquals(con.NIF__c, listPass[0].ID_Card__c);
       

    }
    @isTest
    public static void testUpdate(){
        Contact con = new Contact(FirstName='Test', LastName='1', NIF__c='73429409T');
        insert con;
        Account acc = new Account(Name= 'SALES');
        insert acc;
        DateTime depDate2 = Date.today().addDays(2);
        Flight_Bookings__c fb = new Flight_Bookings__c(Origin__c='Madrid', Destination__c='Bruselas', Class__c='Tourist',
                                                  Departure_Date__c=depDate2, Contact__c = con.Id, Account__c = acc.Id);
        insert fb;
        Passenger__c pas = new Passenger__c(ID_Card__c='73429409T', Age__c = 22, Name='Pepe', Flight_Bookings__c = fb.Id);
        insert pas;

        con.NIF__c = '73429410R';
        update con;
        pas.ID_Card__c = '73429410R';
        update pas;
        List<Passenger__c> listPass = [SELECT ID_Card__c FROM Passenger__c WHERE ID_Card__c =: con.NIF__c];
        System.assertEquals(con.NIF__c, listPass[0].ID_Card__c);

    }
}