force-app/main/default/objects/Contact/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Premium</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credit_Card__c/Credit_Card__c.object-meta.xml
<CustomObject>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>FB-{000000}</displayFormat>
        <label>Credit Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Cards</relationshipLabel>
    <relationshipName>Credit_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Card__c/fields/Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Month__c</fullName>
    <label>Expiration Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Card__c/fields/Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year__c</fullName>
    <label>Expiration Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreditCardHelper.cls
public class CreditCardHelper {
    public static void premium(List<Credit_Card__c> listNews){
        Set<Id> setId = new Set<Id>();
        for(Credit_Card__c cre : listNews){
            if(cre.Owner.LastName != 'Accenture TEST'){
                setId.add(cre.Contact__c);
            }
        }
        
        Map<Id, Contact> mapContact = new Map<Id, Contact>([SELECT Id, Premium__c, OwnerId FROM Contact WHERE Premium__c = true]);
        Map<Id, List<Credit_Card__c>> mapCre = new Map<Id, List<Credit_Card__c>>();
		
        
        for(Credit_Card__c c : listNews){
            Integer month = Integer.valueOf(c.Expiration_Month__c);
            Integer year = Integer.valueOf(c.Expiration_Year__c);
            Date closeDate = Date.newInstance(year, month, 1);
            
        }
    }
}